services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smartstock_app
    restart: unless-stopped
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
      - /var/www/html/node_modules
    environment:
      - APP_ENV=production
    depends_on:
      - db
    ports:
      - "9000:9000"
    networks:
      - smartstock_net

  db:
    image: postgres:16-alpine
    container_name: smartstock_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: smartstock_pro
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - smartstock_net

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smartstock_worker
    restart: unless-stopped
    command: php artisan queue:work database --sleep=3 --tries=3 --max-time=3600
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
    depends_on:
      - db
    networks:
      - smartstock_net

volumes:
  db_data:

networks:
  smartstock_net:
    driver: bridge
